### ISSUE TITLE
Request for sample sketches to connect to telnet server

### ISSUE THREAD

**Issue by JefersonDeLeon** [njh/W5500MacRaw#3]
Hi I'm interested to use mcraw since i found out that is the way to make VLAN tagging ing Wiznet modules for arduino.
Please provide samples utilizing your Library. Thank you

**Comment by njh** [comment]
'W5500MacRaw' just provides a Layer 2 access to raw Ethernet packets.

In order to do Telnet, you will need a separate TCP/IP stack - you can't use the Wiznet one.

I believe someone has a project for [adding W5500 support to LwIP](https://github.com/d-a-v/W5500lwIP) - so maybe you can take a look at that. It looks like it has now been integrated into the [ESP8266 core for Arduino](https://github.com/esp8266/Arduino).

Depending on which Arduino you want to use, you might find that it doesn't have enough memory for a full TCP/IP stack.
